name: graphql_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ferry: ^0.10.4
  gql_http_link: #[latest-version]  
  flutter_riverpod: ^1.0.4
  dotenv: ^4.0.1
  flutter_secure_storage: ^5.0.2
  gql_build: ^0.2.0
  ferry_flutter: ^0.5.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ferry_generator:  ^0.4.4
  build_runner: ^2.1.8


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
